# export PATH=/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
# if [ -f ~/.zshrc ]; then . ~/.zshrc; fi
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval $(pyenv init --path)
eval "$(pyenv init -)"
