# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH
# Path to your oh-my-zsh installation.
export ZSH="/home/yuyouyu/.oh-my-zsh"

POWERLEVEL9K_MODE="nerdfont-complete"
ZSH_THEME="powerlevel10k/powerlevel10k"

# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
        git
        zsh-autosuggestions
	zsh-syntax-highlighting
)
# SSR proxy
export http_proxy="http://127.0.0.1:12333"
export https_proxy="http://127.0.0.1:12333"

source $ZSH/oh-my-zsh.sh

# autojump config
[[ -s /home/yuyouyu/.autojump/etc/profile.d/autojump.sh ]] && source /home/yuyouyu/.autojump/etc/profile.d/autojump.sh
# autoload -U compinit && compinit -u

# You may need to manually set your language environment
export LANG=en_US.UTF-8

# colors config
alias lc='colorls -lA --sd'

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# Homebrew don't auto update
export HOMEBREW_NO_AUTO_UPDATE=true

# source .zprofile
source ~/.zprofile

export TERM=xterm-256color
export EDITOR=vim

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
# [[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm"
PATH="$GEM_HOME/bin:$HOME/.rvm/bin:$PATH" # Add RVM to PATH for scripting
[ -s ${HOME}/.rvm/scripts/rvm ] && source ${HOME}/.rvm/scripts/rvm
